title: Filii Dei
description: "'n Akte van Geloof"
locale: en_ZA
logo: logo.png
disqus_shortname: f1l11d31
share: false
search: true
readtime: true
wpm: 200
dropcap: true
theme: blue
animated_fins: true
fin_color: "255,255,255"
nprogress: true
default_bg: commons.wikimedia.org/header01_gray_lq.jpg
header_bg: commons.wikimedia.org/header01_gray_lq.jpg
author_bg: pinterest.com/header01.jpeg
highlight: 1843e5
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same 
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url: http://0.0.0.0:4000
#url: http://f1l11d31.github.io

# Owner/author information
owner:
  name: f1l11d31
  avatar: f1l11d31.jpeg
  email: null
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description: "'n Akte van Liefde"
  twitter: f1l11d31
  facebook: pages/Filii-Dei/693453224096282
  github: f1l11d31      
  pinterest: f1l11d31
  bitbucket: f1l11d31
  flickr: 130249524@N02
  instagram: null
  google_plus: 104576278582444149019

# Analytics and webmaster tools stuff goes here
google_analytics: UA-56473351-1
google_verify: 
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Hoofblad
    url: /
    external: false
    icon: home
  - title: <i class="fa fa-star"></i> Gunstelinge
    url: /gunstelinge
  - title: Onderwerpe
    url: /onderwerpe
  - title: Indeks
    url: /indeks
  - title: Oorsig
    url: /oorsig

# Skakels met name.
benoemde_skakels:
  gunstelinge: /gunstelinge
  onderwerpe: /onderwerpe
  indeks: /indeks
  oorsig: /oorsig

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Africa/Johannesburg
future:      true
highlighter: pygments
markdown:    kramdown
paginate:    5
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

prose:
  siteurl: 'http://f1l11d31.github.io/'
  relativeLinks: 'http://f1l11d31.github.io/links.jsonp'
  media: 'images/post'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Personal"
              value: personal
            - name: "Engineering"
              value: engineering
            - name: "Mathematics"
              value: mathematics
            - name: "Physics"
              value: physics
            - name: "Psychology"
              value: psychology
            - name: "Photography"
              value: photography
            - name: "Interesting"
              value: interesting
            - name: "Web-Development"
              value: webdevelopment
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "covereffect"
        field:
          element: "select"
          label: "Select Cover Effect"
          placeholder: "Choose Type"
          value:
          options:
            - name: "None"
              value: 
            - name: "slice"
              value: slice
            - name: "push"
              value: push
      - name: "location"
        field:
          element: "text"
          label: "Location"
          placeholder: "Some Place"
      - name: "locationgps"
        field:
          element: "text"
          label: "Location GPS point"
          placeholder: "long, lat"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: false
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false
      - name: "chart"
        field:
          element: "checkbox"
          label: "Chart?"
          value: false
      - name: "charttype"
        field:
          element: "select"
          label: "Select Chart Type"
          placeholder: "Choose Type"
          value:
          options:
            - name: "None"
              value: 
            - name: "pie"
              value: pie
            - name: "serial"
              value: serial
      - name: "jquery"
        field:
          element: "checkbox"
          label: "Require JQuery?"
          value: false


include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
