markdown: kramdown
pygments: true
name: Filii Dei
author: Filius Dei
description: f1l11d31
url: http://f1l11d31.github.io
thumb: https://lh3.googleusercontent.com/-yubFOBTCulA/VJG6GnmrXdI/AAAAAAAAOC0/2_z_BpxTCu8/w1278-h719-no/2%2BChronicles%2B24.13.jpg
